### ISSUE TITLE
Case detail page

### ISSUE THREAD

**Issue by sebastian-gelotte-wipcore** [Wipcore/wipcore#17]

**Comment by sebastian-gelotte-wipcore** [comment]
@mravand could you help me with adding some data to the Case detail pages in sanity? We need:

- Period (String)
- Roles (String I think. We could have a picker here with predefined roles, but that seems overkill)
- Tags (Picker)
- Multiple images (Picker)
- Related cases (Picker)

**Comment by mravand** [comment]
All are doable and sensible.

We can have predefined roles also. Would work like it does in the Heading module. I'll get to it.

**Comment by sebastian-gelotte-wipcore** [comment]
Added "Description" to the list as well.

**Comment by sebastian-gelotte-wipcore** [comment]
@mravand Please change all the modules to fixed fields on this page type according to our discussion. 🎉 😍
