### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by mravand** [Wipcore/wipcore#79]

**Comment by mikaelkarlsson-se** [comment]
The [Analytics plugin for Gatsby](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) has been installed but the correct ID needs to be added and tested at a later date.

**Comment by mikaelkarlsson-se** [comment]
It's placed in body by default 🙌 
https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#head

**Comment by sebastian-gelotte-wipcore** [comment]
Analytics account created under it@wipcore.se account.

UA code: `UA-153420437-1`
