### ISSUE TITLE
Smallish fixes from Concept

### ISSUE THREAD

**Issue by sebastian-gelotte-wipcore** [Wipcore/wipcore#90]
**List from @nartinmielsen:**
01. Background-color på body #f5f5f5
02. Snabba upp text-animation på startsidan lite
03. Gör taggar transperanta istället för vita i default-läge
04. Text-decoration: none, på länkar i footer, och på kontakt
05. Kontaktformulär, gör alla inputs vita eller gör dessa transperanta
06. Alla h3:or som har (WORD), skulle vilja ha (&nbspWORD&nbsp), med andra ord parentes > mellanrum > ord > mellanrum > slutparentes
07. Kontaktsida i mobil, flytta in MAILA under telefonnummer. Och skriv ut mailadress istället för ordet MAILA. (Samma sak i footer)
08. copytext i footer, i mobil, centrerad text. Krymp storlek till 10pt
09. 100% max-width

**Comment by nartinmielsen** [comment]
Skippa den coola menyn som dyker upp vid scroll, och lägga denna i toppen direkt. 

Byta symbol-logo i top-navigationen till namn-logo
Byta namn-logo till symbol-logo i footer

**Comment by nartinmielsen** [comment]
Jag tror vi får se över pixel-effektens påverkan på bilder igen, det är mycket som inte ser så behagligt ut på min skärm :(
